#!/usr/bin/env node
// Builds the framework-free kit into dist/ from the React source. Never edit dist/ by hand.
//   node scripts/build-kit.mjs [--storybook=http://localhost:6006]     (needs Storybook running for the HTML snippets)
//   node scripts/build-kit.mjs --check                                  rebuild, then fail if dist/ differs from git
// Outputs: dist/tokens.css, dist/behaviour.js, dist/tokens.json, dist/kit.css, dist/assets/, dist/html/<Tier>/<Name>/<Story>.html, dist/SUPPORT.md
import { chromium } from 'playwright'
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'

const root = path.resolve(import.meta.dirname, '..')
const dist = path.join(root, 'dist')
const arg = (n, d) => (process.argv.find((a) => a.startsWith(`--${n}=`)) ?? `--${n}=${d}`).split('=').slice(1).join('=')
const sb = arg('storybook', 'http://localhost:6006')
const w = (f, s) => { fs.mkdirSync(path.dirname(path.join(dist, f)), { recursive: true }); fs.writeFileSync(path.join(dist, f), s) }

// Fail before touching dist/ if Storybook is not serving its index.
const index = await (await fetch(`${sb}/index.json`)).json()
fs.rmSync(dist, { recursive: true, force: true })

// 1. Tokens: every custom property from theme.css, light (:root / @theme) and dark (.dark).
const theme = fs.readFileSync(path.join(root, 'src/styles/theme.css'), 'utf8')
const vars = (block) => Object.fromEntries([...block.matchAll(/^\s*(--[\w-]+):\s*([^;]+);/gm)].map((m) => [m[1], m[2].trim()]))
const blocks = (re) => [...theme.matchAll(re)].map((m) => m[1]).join('\n')
const light = vars(blocks(/^(?:@theme|:root)(?: inline)?\s*\{([\s\S]*?)^\}/gm))
const dark = vars(blocks(/^\.dark\s*\{([\s\S]*?)^\}/gm))
const css = (sel, o) => `${sel} {\n${Object.entries(o).map(([k, v]) => `  ${k}: ${v};`).join('\n')}\n}\n`
w('tokens.css', `/* Generated by scripts/build-kit.mjs from src/styles/theme.css. Do not edit. */\n${css(':root', light)}${css('.dark', dark)}`)
w('tokens.json', JSON.stringify({ light, dark }, null, 2) + '\n')

// 2. Assets, then the stylesheet with asset URLs made relative to dist/.
fs.cpSync(path.join(root, 'public/cloudflare'), path.join(dist, 'assets'), { recursive: true })
execFileSync('npx', ['vite', 'build', '-c', 'scripts/kit/vite.config.ts'], { cwd: root, stdio: 'inherit' })
fs.rmSync(path.join(dist, 'kit-entry.js'), { force: true })
fs.writeFileSync(path.join(dist, 'kit.css'), fs.readFileSync(path.join(dist, 'kit.css'), 'utf8').replaceAll('/cloudflare/', './assets/'))

fs.copyFileSync(path.join(root, 'scripts/kit/behaviour.js'), path.join(dist, 'behaviour.js'))

// 3. HTML snippets: the rendered markup of every story, taken twice; markup that differs between the two loads is animated
//    (timers, tickers), so that story is listed as React-only instead of being committed with a random state.
const stories = Object.values(index.entries).filter((e) => e.type === 'story' && !e.title.includes('Foundations'))
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const norm = (h) => { let n = 0; const seen = {}; return h.replace(/(_r_[0-9a-z]+_|:r[0-9a-z]+:)/g, (m) => (seen[m] ??= `_id${++n}_`)).replace(/ style="[^"]*(?:--nav-scroll)[^"]*"/g, '') }
const snap = async (id) => {
  await page.goto(`${sb}/iframe.html?id=${id}&viewMode=story`, { waitUntil: 'load' })
  await page.waitForSelector('#storybook-root > *', { timeout: 15000 }).catch(() => {})
  await page.waitForTimeout(800)
  return page.evaluate(() => ({ html: document.querySelector('#storybook-root').innerHTML, kit: window.__STORYBOOK_PREVIEW__?.currentRender?.story?.parameters?.kit, note: window.__STORYBOOK_PREVIEW__?.currentRender?.story?.parameters?.kitNote }))
}
const rows = []
for (const s of stories) {
  const a = await snap(s.id), b = await snap(s.id)
  const html = norm(a.html)
  const stable = html === norm(b.html)
  const kit = a.kit ?? (stable ? 'static' : 'react-only')
  const file = `html/${s.title}/${s.name.replace(/[^\w-]+/g, '-')}.html`
  if (kit !== 'react-only') w(file, `<!-- ${s.title} / ${s.name} — generated, do not edit. Link kit.css; assets resolve from ../../../assets/ -->\n${html.replaceAll('/cloudflare/', '../../../assets/')}\n`)
  rows.push({ title: s.title, name: s.name, kit, reason: a.note ?? (a.kit ? '' : stable ? '' : 'animated: markup changes between loads') })
}
await browser.close()

// 4. Support table.
const order = { static: 0, vanilla: 1, 'react-only': 2 }
rows.sort((x, y) => x.title.localeCompare(y.title) || x.name.localeCompare(y.name))
const label = { static: 'static', vanilla: 'static + vanilla JS', 'react-only': 'React only' }
w('SUPPORT.md', `# Kit support\n\nGenerated by scripts/build-kit.mjs. A story's \`parameters.kit\` (\`static\` | \`vanilla\` | \`react-only\`) overrides the automatic result.\n\n| Component / story | Support | Note |\n|---|---|---|\n${rows.map((r) => `| ${r.title} / ${r.name} | ${label[r.kit]} | ${r.reason} |`).join('\n')}\n\n${Object.keys(label).map((k) => `- ${label[k]}: ${rows.filter((r) => r.kit === k).length}`).join('\n')}\n`)
console.log(`kit: ${rows.length} stories -> ${rows.filter((r) => r.kit !== 'react-only').length} snippets, ${rows.filter((r) => r.kit === 'react-only').length} React only`)

if (process.argv.includes('--check')) {
  try { execFileSync('git', ['diff', '--exit-code', '--stat', 'dist/'], { cwd: root, stdio: 'inherit' }); console.log('kit: dist/ is up to date') } catch { console.error('kit: dist/ differs from the committed output — rebuild and commit'); process.exit(1) }
}
